#!/usr/bin/env python3
import sys
import argparse
from pathlib import Path
from datetime import datetime

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

def get_status_emoji(status):
    if "archived" in status:
        return "STOP"
    return {"baseline": "OK", "production": "STAR", "testing": "TEST",
            "hypothesis_test": "TEST", "recommended": "STAR", "object_centered": "TEST"}.get(status, "?")

def build_status_map():
    from mouse_extensions.preprocessing.presets import VERSION_HIERARCHY
    status_map = {}
    for status, presets in VERSION_HIERARCHY.items():
        if isinstance(presets, list):
            for p in presets:
                status_map[p] = status
        elif isinstance(presets, str):
            status_map[presets] = "recommended"
    return status_map

def generate_dataset_index():
    from mouse_extensions.preprocessing.presets import VERSION_HIERARCHY, PRESETS
    status_map = build_status_map()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    lines = [
        "# Dataset & Preset Index",
        "",
        "> **Auto-generated from presets.py** - Do not edit manually",
        "> Last updated: " + now,
        "",
        "## Related Documents (Manual)",
        "",
        "| Document | Location | Type |",
        "|----------|----------|------|",
        "| PP/MVG Analysis | docs/theory/PP_FX_MVG_ANALYSIS.md | Qualitative |",
        "| Hypothesis Plan | docs/experiments/HYPOTHESIS_VERIFICATION_PLAN.md | Qualitative |",
        "",
        "---",
        "",
        "## Active Presets",
        "",
        "| Preset | Status | Paradigm | Transform | Zoom | PP | Description |",
        "|--------|--------|----------|-----------|------|-----|-------------|",
    ]

    for name, preset in sorted(PRESETS.items()):
        status = status_map.get(name, "unknown")
        if "archived" in status or "deprecated" in status:
            continue
        emoji = get_status_emoji(status)
        paradigm = str(preset.get("paradigm", "-"))[:12]
        transform = str(preset.get("transform", "-"))
        
        if preset.get("adaptive_zoom"):
            zr = preset.get("zoom_range", [1.0, 1.8])
            zs = str(preset.get("zoom_scope", "global"))[:3]
            zoom = zs + " " + str(zr)
        else:
            zoom = "-"
        
        pp = "256" if preset.get("pp_method") in ["shift_to_256", "force_256"] else "var"
        desc = str(preset.get("description", "-"))[:40]
        lines.append("| " + name + " | " + emoji + " " + status + " | " + paradigm + " | " + transform + " | " + zoom + " | " + pp + " | " + desc + " |")

    lines.extend([
        "",
        "## Archived Presets",
        "",
        "| Preset | Category | Reason |",
        "|--------|----------|--------|",
    ])

    for name in sorted(PRESETS.keys()):
        status = status_map.get(name, "")
        if "archived" in status:
            reason = status.replace("archived_", "").replace("_", " ")
            r = str(PRESETS[name].get("reason", "-"))
            lines.append("| ~~" + name + "~~ | " + reason + " | " + r + " |")

    lines.extend(["", "---", "", "*Auto-generated by generate_preset_docs.py*"])
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    
    generated_dir = PROJECT_ROOT / "docs" / "generated"
    if not args.dry_run:
        generated_dir.mkdir(parents=True, exist_ok=True)
    
    content = generate_dataset_index()
    output_path = generated_dir / "DATASET_INDEX.md"
    
    if args.dry_run:
        print("[DRY-RUN] Would write:", output_path)
        print(content[:800] + "...")
    else:
        with open(output_path, "w") as f:
            f.write(content)
        print("Generated:", output_path)
    
    print("\nManual docs (not touched): docs/theory/*, docs/analysis/*, docs/experiments/*")

if __name__ == "__main__":
    main()
