#!/usr/bin/env python3
"""
Generate documentation from presets.py (SSOT).
Run after modifying presets.py to keep docs in sync.

Usage:
    python mouse_extensions/scripts/generate_preset_docs.py
"""

import sys
from pathlib import Path
from datetime import datetime

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

def generate_dataset_index():
    """Generate DATASET_INDEX.md from VERSION_HIERARCHY."""

    from mouse_extensions.preprocessing.presets import VERSION_HIERARCHY, PRESETS

    # Build status map
    status_map = {}
    for status, presets in VERSION_HIERARCHY.items():
        if isinstance(presets, list):
            for p in presets:
                status_map[p] = status
        elif isinstance(presets, str):
            status_map[presets] = "recommended"

    # Status emoji
    status_emoji = {
        "stable": "✅",
        "baseline": "✅",
        "production": "⭐",
        "testing": "🔬",
        "hypothesis_test": "🔬",
        "recommended": "⭐",
        "archived": "⛔",
        "archived_geometry_broken": "⛔",
        "archived_superseded": "⛔",
        "archived_native": "⛔",
        "archived_experimental": "⛔",
        "archived_deprecated": "⛔",
        "deprecated": "⛔",
        "object_centered": "🔬",
    }

    # Generate markdown
    lines = [
        "# Dataset & Preset Index",
        "",
        "> **Auto-generated from `presets.py`**",
        f"> Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Active Presets",
        "",
        "| Preset | Status | Category | Description |",
        "|--------|--------|----------|-------------|",
    ]

    # Active presets
    active_categories = ["baseline", "production", "stable", "testing", "hypothesis_test", "object_centered"]
    for name, preset in sorted(PRESETS.items()):
        status = status_map.get(name, "unknown")
        if any(cat in status for cat in ["archived", "deprecated"]):
            continue
        emoji = status_emoji.get(status, "❓")
        desc = preset.get("description", "-")[:50]
        lines.append(f"| {name} | {emoji} {status} | {preset.get('paradigm', '-')[:15]} | {desc} |")

    lines.extend([
        "",
        "## Archived Presets",
        "",
        "| Preset | Reason |",
        "|--------|--------|",
    ])

    # Archived presets
    for name in sorted(PRESETS.keys()):
        status = status_map.get(name, "")
        if "archived" in status or "deprecated" in status:
            reason = status.replace("archived_", "").replace("_", " ")
            lines.append(f"| ~~{name}~~ | {reason} |")

    lines.extend([
        "",
        "## VERSION_HIERARCHY",
        "",
        "```python",
    ])

    for key, value in VERSION_HIERARCHY.items():
        lines.append(f'"{key}": {value},')

    lines.extend([
        "```",
        "",
        "---",
        "",
        "*Auto-generated by `generate_preset_docs.py`*",
    ])

    return "\n".join(lines)


def main():
    output_dir = PROJECT_ROOT / "docs" / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate dataset index
    content = generate_dataset_index()
    output_path = output_dir / "DATASET_INDEX.md"
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Generated: {output_path}")

    print("\nDone! Run this script after modifying presets.py.")


if __name__ == "__main__":
    main()
