# Dataset: D10_3
# M3: D7_1 + Homography + Adaptive Zoom (5% FG target)
# Generated: 2026-01-24 17:58:57

_name: D10_3
_description: "M3: D7_1 + Homography + Adaptive Zoom (5% FG target)"
_category: precision_homography
_preprocessing:
  paradigm: precision_homography
  transform: homography
  target_fx: 548.9937744140625
  output_size: 512

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M3/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M3/data_mouse_val.txt

_stats:
  num_train: 3238
  num_val: 359
