# =============================================================================
# Dataset: D7_1
# =============================================================================
# Individual scale, geometrically correct (Non-temporal split)
# =============================================================================

_name: D7_1
_description: "Individual scale preprocessing with geometric correction"
_split_type: random  # Not temporal

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_1/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_1/data_mouse_val.txt
