# =============================================================================
# Dataset: D7_1_t
# =============================================================================
# Individual scale + Temporal split (train:val:test = 1:1:1)
# =============================================================================

_name: D7_1_t
_description: "D7.1 with temporal train/val/test split"
_split_type: temporal

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_1_t/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_1_t/data_mouse_val.txt

inference:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_1_t/data_mouse_test.txt
