# =============================================================================
# Dataset: D7_t
# =============================================================================
# Individual scale, geometrically correct (Temporal split)
# =============================================================================

_name: D7_t
_description: "Temporal split - train on earlier frames, validate on later"
_split_type: temporal  # Temporal split for generalization testing

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_t/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/D7_t/data_mouse_val.txt
