# Dataset: M0
# BASELINE: no centering (original PP), no normalization (raw translation)
# Generated: 2026-01-29 16:48:54

_name: M0
_description: "BASELINE: no centering (original PP), no normalization (raw translation)"
_category: recentered_affine
_preprocessing:
  paradigm: recentered_affine
  transform: affine
  target_fx: 549.0
  output_size: 512

training:
  dataset:
    dataset_path: ~/data/preprocessed/FaceLift_mouse/M0/data_mouse_train.txt

validation:
  dataset_path: ~/data/preprocessed/FaceLift_mouse/M0/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
