# Dataset: M3_2b
# M3_2 + conservative zoom
# Generated: 2026-01-26 15:59:06

_name: M3_2b
_description: "M3_2 + conservative zoom"
_category: precision_homography
_preprocessing:
  paradigm: precision_homography
  transform: homography
  target_fx: 548.9937744140625
  output_size: 512

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M3_2b/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M3_2b/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
