# Dataset: M3_3
# M3_2 + safe zoom (0% clipping, PP=256)
# Generated: 2026-01-26 15:57:26

_name: M3_3
_description: "M3_2 + safe zoom (0% clipping, PP=256)"
_category: precision_homography
_preprocessing:
  paradigm: precision_homography
  transform: homography
  target_fx: 548.9937744140625
  output_size: 512

training:
  dataset:
    dataset_path: ~/data/preprocessed/FaceLift_mouse/M3_3/data_mouse_train.txt

validation:
  dataset_path: ~/data/preprocessed/FaceLift_mouse/M3_3/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
