# Dataset: M4
# Object-centered + PP correction (max coverage)
# Generated: 2026-01-26 15:52:39

_name: M4
_description: "Object-centered + PP correction (max coverage)"
_category: object_centered_mvg
_preprocessing:
  paradigm: object_centered_mvg
  transform: homography
  target_fx: 548.9937744140625
  output_size: 512

training:
  dataset:
    dataset_path: ~/data/preprocessed/FaceLift_mouse/M4/data_mouse_train.txt

validation:
  dataset_path: ~/data/preprocessed/FaceLift_mouse/M4/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
