# Dataset: M5_5
# ABLATION E: centering O (PP=256) + per-view norm (each cam=2.7)
# Generated: 2026-01-28 17:10:20

_name: M5_5
_description: "ABLATION E: centering O (PP=256) + per-view norm (each cam=2.7)"
_category: recentered_affine
_preprocessing:
  paradigm: recentered_affine
  transform: affine
  target_fx: 549.0
  output_size: 512

training:
  dataset:
    dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M5_5/data_mouse_train.txt

validation:
  dataset_path: /home/joon/data/preprocessed/FaceLift_mouse/M5_5/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
