# Dataset: M5h_2
# M3_2b + re-centered cameras + uniform distance norm. Per-sample zoom. RECOMMENDED.
# Generated: 2026-01-27 19:16:09

_name: M5h_2
_description: "M3_2b + re-centered cameras + uniform distance norm. Per-sample zoom. RECOMMENDED."
_category: recentered_homography
_preprocessing:
  paradigm: recentered_homography
  transform: homography
  target_fx: 548.9938
  output_size: 512

training:
  dataset:
    dataset_path: ~/data/preprocessed/FaceLift_mouse/M5h_2/data_mouse_train.txt

validation:
  dataset_path: ~/data/preprocessed/FaceLift_mouse/M5h_2/data_mouse_val.txt

_stats:
  num_train: 3240
  num_val: 360
